#!/bin/bash
source ~/.bashrc
workon django-roster
date >> /home/carpenoctem/django-roster/wsgi/cnto/warnings.log
cd /home/carpenoctem/django-roster/wsgi/cnto
PYTHONPATH=`pwd` python scripts/add_and_update_warnings.py >> /home/carpenoctem/django-roster/wsgi/cnto/warnings.log

