#!/bin/bash
source ~/.bashrc
workon django-roster
cd /home/carpenoctem/django-roster/wsgi/cnto
PYTHONPATH=`pwd`:/home/carpenoctem/django-roster/libs python scripts/update_attendance.py >> /home/carpenoctem/django-roster/wsgi/cnto/warnings.log
